language: ruby
script: bundle exec rake # do the default task
before_install:
  - gem install bundler
  - bundle install
  - bundle exec rake db:migrate
os:
  - linux
  - osx
rvm:
  - "1.9.3"
  - "1.8.7"
  - "2.0.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "ruby-head"
matrix:
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: "1.8.7"
    - rvm: "1.9.3"
    - rvm: "2.3"
addons:
  code_climate:
    repo_token: 7a432be524fe17ff819eba0385b9e6fae891674470c2b9bf540f4a0e748f2b9c
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/40526a0210595f183a60
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
