#
# added by nicb
#
development:
  secret_key_base: __EMUForm_development_secret__
  secret_token: __EMUForm_development_secret_token__

test:
  secret_key_base: __EMUForm_test_secret__
  secret_token: __EMUForm_development_secret_token__

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token: <%= ENV['EMUFORM_SECRET_TOKEN'] %>
