# 2015-07-23 RICHARD:
# THIS IS A SAMPLE FOR social_keys.yml which is git-ignored as it should be, because it will have your keys in it.
test:
  facebook_key: '1667484636870927'
  facebook_secret: 'I dont have a secret for this :-('

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: 'emuform-1199'
  google_secret: "YOUR_SECRET"

development:
  facebook_key: '1667484636870927'
  facebook_secret: 'I dont have a secret for this :-('

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: 'emuform-1199'
  google_secret: "YOUR_SECRET"

production:
  facebook_key: '1667484636870927'
  facebook_secret: 'I dont have a secret for this :-('

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"
